import AppKit
import UniformTypeIdentifiers

/// Polls NSPasteboard.general and turns new content into Clips.
@MainActor
final class ClipboardMonitor {
    private let store: ClipStore
    private var timer: Timer?
    private var lastChangeCount: Int
    private var suppressNext = false

    /// Skip capturing the next pasteboard change (used by cut, so the clip
    /// being removed doesn't immediately re-enter history).
    func suppressNextChange() { suppressNext = true }

    private static let transientTypes: [NSPasteboard.PasteboardType] = [
        .init("org.nspasteboard.TransientType"),
        .init("org.nspasteboard.ConcealedType"),
        .init("org.nspasteboard.AutoGeneratedType"),
        .init("com.agilebits.onepassword"),
        .init("com.apple.PasswordManager.Password"),
    ]

    init(store: ClipStore) {
        self.store = store
        lastChangeCount = NSPasteboard.general.changeCount
        timer = Timer.scheduledTimer(withTimeInterval: 0.2, repeats: true) { [weak self] _ in
            Task { @MainActor in self?.check() }
        }
        timer.map { RunLoop.main.add($0, forMode: .common) }
    }

    private func check() {
        let pb = NSPasteboard.general
        guard pb.changeCount != lastChangeCount else { return }
        lastChangeCount = pb.changeCount

        if suppressNext {
            suppressNext = false
            return
        }

        guard let types = pb.types, !types.isEmpty else { return }
        if Self.transientTypes.contains(where: types.contains) { return }

        let sourceApp = NSWorkspace.shared.frontmostApplication
        var clip: Clip?

        // Files first: file copies also carry string representations.
        if let urls = pb.readObjects(forClasses: [NSURL.self], options: [.urlReadingFileURLsOnly: true]) as? [URL],
           !urls.isEmpty {
            let paths = urls.map(\.path)
            clip = Clip(kind: .file,
                        text: paths.joined(separator: "\n"),
                        filePaths: paths,
                        contentHash: ("file:" + paths.joined(separator: "|")).sha256Hash)
        } else if let imageData = imageData(from: pb) {
            clip = makeImageClip(data: imageData)
        } else if let str = pb.string(forType: .string), !str.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            let trimmed = str.trimmingCharacters(in: .whitespacesAndNewlines)
            let kind: ClipKind = Self.isLink(trimmed) ? .link : .text
            clip = Clip(kind: kind, text: str, contentHash: ("text:" + str).sha256Hash)
        }

        guard var newClip = clip else { return }
        newClip.appName = sourceApp?.localizedName
        newClip.bundleID = sourceApp?.bundleIdentifier
        store.add(newClip)
    }

    private static func isLink(_ s: String) -> Bool {
        guard !s.contains("\n"), !s.contains(" "),
              let url = URL(string: s),
              let scheme = url.scheme?.lowercased() else { return false }
        return ["http", "https"].contains(scheme) && url.host != nil
    }

    private func imageData(from pb: NSPasteboard) -> Data? {
        for type in [NSPasteboard.PasteboardType.png, .tiff] {
            if let data = pb.data(forType: type), !data.isEmpty { return data }
        }
        return nil
    }

    private func makeImageClip(data: Data) -> Clip? {
        guard let rep = NSBitmapImageRep(data: data) else { return nil }
        let hash = data.sha256Hash
        // Skip payload rewrite if this exact image is already stored.
        if store.clips.first(where: { $0.contentHash == "image:" + hash }) != nil {
            return Clip(kind: .image, contentHash: "image:" + hash)
        }
        let id = UUID()
        let imageName = "\(id.uuidString).png"
        let thumbName = "\(id.uuidString).jpg"
        guard let png = rep.representation(using: .png, properties: [:]) else { return nil }
        let imagesURL = store.imagesURL, thumbsURL = store.thumbsURL
        let thumb = Self.thumbnailJPEG(from: rep, maxDimension: 640)
        DispatchQueue.global(qos: .userInitiated).async {
            try? png.write(to: imagesURL.appendingPathComponent(imageName), options: .atomic)
            try? thumb?.write(to: thumbsURL.appendingPathComponent(thumbName), options: .atomic)
        }
        return Clip(id: id,
                    kind: .image,
                    imageFile: imageName,
                    thumbFile: thumb != nil ? thumbName : nil,
                    pixelWidth: rep.pixelsWide,
                    pixelHeight: rep.pixelsHigh,
                    contentHash: "image:" + hash)
    }

    private static func thumbnailJPEG(from rep: NSBitmapImageRep, maxDimension: CGFloat) -> Data? {
        let w = CGFloat(rep.pixelsWide), h = CGFloat(rep.pixelsHigh)
        guard w > 0, h > 0 else { return nil }
        let scale = min(1, maxDimension / max(w, h))
        let tw = max(1, Int(w * scale)), th = max(1, Int(h * scale))
        guard let cg = rep.cgImage else { return nil }
        guard let ctx = CGContext(data: nil, width: tw, height: th, bitsPerComponent: 8, bytesPerRow: 0,
                                  space: CGColorSpace(name: CGColorSpace.sRGB)!,
                                  bitmapInfo: CGImageAlphaInfo.premultipliedLast.rawValue) else { return nil }
        ctx.interpolationQuality = .high
        ctx.draw(cg, in: CGRect(x: 0, y: 0, width: tw, height: th))
        guard let scaled = ctx.makeImage() else { return nil }
        let outRep = NSBitmapImageRep(cgImage: scaled)
        return outRep.representation(using: .jpeg, properties: [.compressionFactor: 0.85])
    }
}
